apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  creationTimestamp: null
  labels:
    app: redis-build
    name: redis
  name: redis-build
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: redis:latest
  runPolicy: Serial
  source:
    contextDir: image
    git:
      uri: https://github.com/rarodrigues9/redis-openshift.git
    type: Git
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: centos7:latest
        namespace: openshift
    type: Docker
  triggers: []
status:
  lastVersion: 0
