apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: rhel7
  namespace: openshift
spec:
  tags:
  - from:
      kind: DockerImage
      name: registry.access.redhat.com/rhel7:7.9-983.1679306060
    name: latest
    referencePolicy:
      type: Source
