apiVersion: v1
items:
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: redis-sentinel
      redis-sentinel: "true"
    name: redis-sentinel
  spec:
    replicas: 3
    selector:
      app: redis-sentinel
      redis-sentinel: "true"
    template:
      metadata:
        labels:
          app: redis-sentinel
          redis-sentinel: "true"
      spec:
        containers:
        - image: image-registry.openshift-image-registry.svc:5000/redis/redis
          imagePullPolicy: Always
          name: sentinel
          env:
            - name: SENTINEL
              value: "true"
          volumeMounts:
            - mountPath: /redis-master-data
              name: data 
          ports:
            - containerPort: 26379
          resources: {}
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
          - name: data
            emptyDir: {}
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - sentinel
        from:
          kind: ImageStreamTag
          name: redis:latest
          namespace: redis
      type: ImageChange
  status: {}
kind: List
metadata: {}
